FROM python:3.7
#MAINTAINER asher

# set unbuffered mode
ENV PYTHONUNBUFFERD 1

WORKDIR /app

# copy requirements to docker image
COPY requirements.txt /app/requirements.txt
# install requirements to docker image
RUN pip install -r requirements.txt

# copy source code
COPY . /app 

# runserver
CMD python manage.py runserver 0.0.0.0:80